//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgencyApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class RealEstateAgencyEntities : DbContext
    {
        public static RealEstateAgencyEntities _context;
        public RealEstateAgencyEntities()
            : base("name=RealEstateAgencyEntities")
        {
        }
        public static RealEstateAgencyEntities GetContext()
        {
            if (_context == null)
            {
                _context = new RealEstateAgencyEntities();
            }
            return _context;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agents> agents { get; set; }
        public virtual DbSet<apartments> apartments { get; set; }
        public virtual DbSet<apartments_demands> apartments_demands { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<deals> deals { get; set; }
        public virtual DbSet<Demands> Demands { get; set; }
        public virtual DbSet<districts_> districts_ { get; set; }
        public virtual DbSet<house_demands> house_demands { get; set; }
        public virtual DbSet<houses> houses { get; set; }
        public virtual DbSet<land_demands> land_demands { get; set; }
        public virtual DbSet<lands> lands { get; set; }
        public virtual DbSet<supplies> supplies { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
